### ISSUE TITLE
[BUG]: The func hho_f5 may be incorrect 

### ISSUE THREAD

**Issue by Chanmoey** [thieu1995/metaheuristics#5]
### Description of the bug

your code:
```python
def hho_f5(solution=None, problem_size=None):
    return np.sum(100*(solution[1:problem_size] - (solution[0:problem_size-1]))**2 + (solution[0:problem_size-1]-1)**2)
```
The correct code would be the following：
```python
def hho_f5(solution=None, problem_size=None):
    return np.sum(100*(solution[1:problem_size] - (solution[0:problem_size-1]) ** 2)**2 + (solution[0:problem_size-1]-1)**2)
```

### Steps To Reproduce

Nothing.

### Additional Information

Nothing.

**Comment by thieu1995** [comment]
@Chanmoey ,

This is draft repository for Mealpy library and Opfunu library. I rarely use it now.
You can check out latest benchmark function on https://github.com/thieu1995/opfunu

**Comment by xm1490** [comment]
来信收到。谢谢。徐明
